### PR TITLE
Update readme (DCNE-186)

### LINKED ISSUE #23: Test Issue for auto approval status changes (DCNE-186)

### PR DESCRIPTION
**Pull request by samiib**
Closes #23

### CODE REVIEW

**Comment by samiib** [comment]
test3

**Comment by samiib** [comment]
test4

**Comment by samiib** [comment]
test5

**Comment by samiib** [comment]
test6

**Comment by samiib** [comment]
test7

**Review by SamDslayer — APPROVED** [review]
LGTM

**Review by SamDslayer — CHANGES_REQUESTED** [review]
Test

**Review by SamDslayer — APPROVED** [review]

**Pull request merged**
